---
# file: bind.yml

- name: Install bind
  yum: name=bind state=installed

- name: copy named conf
  template: src=bind/named.conf dest=/etc/named.conf

- name: /var/named permission change
  file: path=/var/named mode=0770

- name: domain zone file setup
  template: src=bind/example.com dest=/var/named/{{ domain_name }} owner=named group=named mode=0660

- name: reverse zone file setup
  template: src=bind/0.168.192.in-addr.arpa dest=/var/named/{{ reverse_name }} owner=named group=named mode=0660

- name: named start
  service: name=named state=started enabled=yes
