---
# file: dhcp.yml

- name: Install dhcp
  yum: name=dhcp state=installed

- name: setup dhcpd conf
  template: src=dhcp/dhcpd.conf dest=/etc/dhcp/dhcpd.conf
  when: dhcp_network_address is defined

- name: start dhcpd
  service: name=dhcpd state=started enabled=yes
